### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by tyujrtuy** [extremeblackliu/LeiGodAutoTimer#4]
兄弟。雷神更新8.1.7后该插件失效了，有后续更新计划么

**Comment by eeacks** [comment]
‍雷神8.1.7 我两台电脑都测试了没有问题，重新安装过雷神也是没有问题。

**Comment by eeacks** [comment]
两台电脑反复测试都没有问题，不知道什么原因，找不到原因不打算解决了。
