### ISSUE TITLE
雷神最新内测版本10.0.3.1无法正常启动加速器

### ISSUE THREAD

**Issue by LHWKALAD** [extremeblackliu/LeiGodAutoTimer#5]
启动加速器报错应用程序无法正常启动（0xc0000142）。删除dll插件后恢复正常。
内测包在这里
https://wwtt.lanzouw.com/iGgmH0ozeyfi
密码:bb8w

**Comment by eeacks** [comment]
雷神10.0直接整个变浏览器了...我会看看的

**Comment by heheda2033** [comment]
正式版10.0.4.2同样报错
---------------------------
leigod.exe - 应用程序错误
---------------------------
应用程序无法正常启动(0xc0000142)。请单击“确定”关闭应用程序。 
---------------------------
确定   
---------------------------

**Comment by eeacks** [comment]
正式版已经更新到10.0，之后我会看看，有别的事情忙着

**Comment by eeacks** [comment]
整合到 https://github.com/extremeblackliu/LeiGodAutoTimer/issues/6
